// Generated by CoffeeScript 2.2.1
var DEFAULT_EMBEDDED_NAME, __express, register, registeredInExpress;

import {
  coffee
} from "coffeescript";

import {
  slm
} from "slm";

DEFAULT_EMBEDDED_NAME = 'coffee';

registeredInExpress = false;

// slmCoffee.register(...) is to keep compatibility with existing Slm plugins
register = function(template, engineName, options) {
  if (!engineName) {
    engineName = DEFAULT_EMBEDDED_NAME;
  }
  template.registerEmbeddedFunction(engineName, function(string) {
    var result;
    result = '<script type="text/javascript">';
    result += coffee.compile(string);
    result += '</script>';
    return result;
  });
  return coffee;
};

// slmCoffee.__express(...) allows us to register as an ExpressJS template engine
__express = function(filePath, options, callback) {
  // Do not register every call
  if (!registeredInExpress) {
    register(slm.template, DEFAULT_EMBEDDED_NAME);
    registeredInExpress = true;
  }
  return slm.__express(filePath, options, callback);
};

export {
  register,
  __express
};
